export const URLS = {
    LOGIN: '/auth/signin',
    SIGNUP: '/auth/signup',
    SEND_VERIFICATION_EMAIL: '/chasescroll/verification/send-email',
    VERIFY_TOKEN: '/chasescroll/verification/verify-token',
    RESET_PASSWORD: '/chasescroll/verification/change-password',
    GET_POSTS: '/feed/get-user-and-friends-posts',
    GET_USER_DETAILS: '/user/publicprofile',
    GET_USER_PRIVATE_PROFILE: '/user/privateprofile',
    GET_POST_BY_ID: '/feed/get-post',
    LIKE_POST: '/feed/like-post',
    CREATE_POST: '/feed/create-post',
    UPLOAD_VIDEO: '/resource-api/upload-video',
    UPLOAD_IMAGE: '/resource-api/upload-image',
    GET_ALL_COMMENTS: '/feed/get-all-comments/',
    ADD_COMMENT: '/feed/add-comment',
    LIKE_COMMENT: '/feed/like-comment',
    DELETE_COMMENT: '/feed/remove-comment/',
    GET_ALL_SUBCOMMENTS: '/feed/get-all-sub-comments',
    CREATE_SUB_COMMENT: '/feed/add-sub-comment',
    LIKE_SUB_COMMENT: '/feed/like-sub-comment',
    DELETE_SUB_COMMENT: '/feed/remove-sub-comment',
    CREATE_REPORT: '/report/report',
    REMOVE_FRIEND: '/user/remove-friend/',
    ADD_FRIEND: '/user/send-friend-request',
    BLOCK_USER: '/user/block',
    GET_SUGGESTED_FRIENDS: "/user/suggest-connections",
    JOIN_GROUP: "/group/join-group",
    LEAVE_GROUP: "/group/leave-group",
    EVENT_TYPE: "/events/get-event-types",
    JOINED_EVENT: "/events/joined-events/",
    All_EVENT: "/events/events",
    CREATE_TICKET: "/events/create-ticket",
    GET_EVENTS_TYPES: "/events/get-event-types",
    CREATE_DRAFT: "/events/create-draft",
    UPDATE_DRAFT: "/events/update-draft",
    CREATE_EVENT_FROM_DRAFT: "/events/create-event-from-draft",
    GET_DRAFT: "/events/drafts",
    PAST_EVENT: "/events/get-past-events",
    SAVED_EVENT: "/events/get-saved-events?typeID="
}

export const IMAGE_URL = process.env.NEXT_PUBLIC_RESOURCE_URL;
    CREATE_REPORT: '/report/report',
    JOINED_GROUPS: '/group/joined-groups',
    JOIN_GROUP: '/group/join-group',
    FIND_GROUPS: '/group/find-groups',
    GROUP_GROUP: '/group/group',
    GET_GROUP_REQUESTS: '/group/get-requests',
    CREATE_COMMUNITY: '/group/create-group',
    GET_GROUP_MESSAGES:'/feed/get-all-group-posts'
}

export const RESOURCE_BASE_URL = process.env.NEXT_PUBLIC_RESOURCE_URL;